# Generated by Django 4.1.3 on 2022-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Dob', models.DateField()),
                ('State', models.CharField(choices=[('CHENNAI', 'CHENNAI'), ('HYDERABAD', 'HYDERABAD'), ('BENGULURU', 'BENGULURU'), ('MUMBAI', 'MUMBAI'), ('NOIDA', 'NOIDA')], max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Profile_pic', models.ImageField(blank=True, upload_to='pimages')),
                ('File_upload', models.FileField(blank=True, upload_to='files')),
            ],
        ),
    ]
